### ISSUE TITLE
Filling out user.json

### ISSUE THREAD

**Issue by tensigh** [aeluro1/geddit#9]
Two issues on filling out user.json:

1. For the Reddit section, one field is "client_id", but Reddit doesn't specify which field this is. I've taken a guess but do you have some feedback? 
2. For the imgur fields, under "client_id" it lists room for 3 keys, but I only got 2 from imgur, the client ID and client secret. Is this enough?

**Comment by aeluro1** [comment]
1. It's the sequence of characters right next to the app name, at the top. Not the secret.
2. Yeah, that's just an option to include multiple ids if you're downloading tons of imgur content, so you don't hit Imgur's rate limits. You can just include one client ID.
